In [50]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split  # divide korar jonno library
from sklearn.linear_model import LinearRegression  # Model built er jonno library


In [51]:
data = pd.read_csv("Company.csv")
data.head(10)

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0
5              2.9  56642.0
6              3.0  60150.0
7              3.2  54445.0
8              3.2  64445.0
9              3.7  57189.0

In [52]:
# data set ke divide kora
# IV or DV te

# iloc[row,col]
real_x = data.iloc[:,0].values    # real_x -->> IV rakbo == input er data
real_x = real_x.reshape(-1,1)     # 1D Array na korle vul asbo pore   
print(real_x)                     # Array data -- e output asce


[[ 1.1]
 [ 1.3]
 [ 1.5]
 [ 2. ]
 [ 2.2]
 [ 2.9]
 [ 3. ]
 [ 3.2]
 [ 3.2]
 [ 3.7]
 [ 3.9]
 [ 4. ]
 [ 4. ]
 [ 4.1]
 [ 4.5]
 [ 4.9]
 [ 5.1]
 [ 5.3]
 [ 5.9]
 [ 6. ]
 [ 6.8]
 [ 7.1]
 [ 7.9]
 [ 8.2]
 [ 8.7]
 [ 9. ]
 [ 9.5]
 [ 9.6]
 [10.3]
 [10.5]]


In [53]:
real_y = data.iloc[:,1].values    # DV rakbo == output er data
real_y = real_y.reshape(-1,1)     # 1D Array na korle vul asbo pore   
print(real_y)                     # Array data -- e output asce

[[ 39343.]
 [ 46205.]
 [ 37731.]
 [ 43525.]
 [ 39891.]
 [ 56642.]
 [ 60150.]
 [ 54445.]
 [ 64445.]
 [ 57189.]
 [ 63218.]
 [ 55794.]
 [ 56957.]
 [ 57081.]
 [ 61111.]
 [ 67938.]
 [ 66029.]
 [ 83088.]
 [ 81363.]
 [ 93940.]
 [ 91738.]
 [ 98273.]
 [101302.]
 [113812.]
 [109431.]
 [105582.]
 [116969.]
 [112635.]
 [122391.]
 [121872.]]


In [56]:
# Supervised learning e ... dataset -->> traing ar testing dataset e divided kora hoy
# training er data ... 70-80 % rakte hbe er theke besi ora kom hote parbe na 
# testing er data ... baki % e rakbo


training_x,testing_x,training_y,testing_y = train_test_split(real_x,real_y,test_size = 0.3,random_state = 0)  # data set split kortesi
            # randodm_state = 0 na dile ans ekbar ekta asbo 

In [57]:

Lin = LinearRegression() # ei cls er object ---> Lin
Lin.fit(training_x,training_y) # ei khane ei Model train kora hoise # Model ke fit kora hoise  --> fit = cls e 2 ta argument nei ei gula Training er sate related

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [58]:
# Prediction korbo ekhon

Pred_y = Lin.predict(testing_x)

In [59]:
testing_y[3]  # real value -- 3 no data er jonno   # extual result

array([63218.])

In [60]:
Pred_y[3]     # 3 no data er Prediction

array([63282.41035735])

In [ ]:
 # Prediction pray kasa kasi