In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


In [2]:
data = pd.read_csv("Company.csv")
data.head(10)

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0
5              2.9  56642.0
6              3.0  60150.0
7              3.2  54445.0
8              3.2  64445.0
9              3.7  57189.0

In [4]:
real_x = data.iloc[:,0].values    
real_x = real_x.reshape(-1,1)      
print(real_x)   

[[ 1.1]
 [ 1.3]
 [ 1.5]
 [ 2. ]
 [ 2.2]
 [ 2.9]
 [ 3. ]
 [ 3.2]
 [ 3.2]
 [ 3.7]
 [ 3.9]
 [ 4. ]
 [ 4. ]
 [ 4.1]
 [ 4.5]
 [ 4.9]
 [ 5.1]
 [ 5.3]
 [ 5.9]
 [ 6. ]
 [ 6.8]
 [ 7.1]
 [ 7.9]
 [ 8.2]
 [ 8.7]
 [ 9. ]
 [ 9.5]
 [ 9.6]
 [10.3]
 [10.5]]


In [4]:
real_y = data.iloc[:,1].values    
real_y = real_y.reshape(-1,1)      
print(real_y)                    

[[ 39343.]
 [ 46205.]
 [ 37731.]
 [ 43525.]
 [ 39891.]
 [ 56642.]
 [ 60150.]
 [ 54445.]
 [ 64445.]
 [ 57189.]
 [ 63218.]
 [ 55794.]
 [ 56957.]
 [ 57081.]
 [ 61111.]
 [ 67938.]
 [ 66029.]
 [ 83088.]
 [ 81363.]
 [ 93940.]
 [ 91738.]
 [ 98273.]
 [101302.]
 [113812.]
 [109431.]
 [105582.]
 [116969.]
 [112635.]
 [122391.]
 [121872.]]


In [5]:
training_x,testing_x,training_y,testing_y = train_test_split(real_x,real_y,test_size = 0.3,random_state = 0)

In [6]:
Lin = LinearRegression() 
Lin.fit(training_x,training_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [7]:
# Prediction korbo ekhon

Pred_y = Lin.predict(testing_x)

In [ ]:
# y = b0 + b1x
        # b0 = intercept_
        # b1 = coef_

In [8]:
Lin.coef_  # b1

array([[9360.26128619]])

In [9]:
Lin.intercept_  # b0

array([26777.3913412])

In [11]:
# Now Equation formate e liktesi

# first data diya dektesi ...ischa korle sob gular jonno dekte parmu

26777.3913412 + 9360.26128619*1.1   # Prediction equation diya   == Accuracy 70-80%

37073.678756009

In [12]:
26777.3913412 + 9360.26128619*1.3  #for 2nd data   === prediction

38945.731013247