In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('Position_Salaries.csv')
data.head(10)

Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5     Region Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000

###### SLR --> kora jabe ekoi Department,ekoi Lavel --- er upor # but Multiple Level Or Department er jonno kora jabe nah = Limitation eta

# DataSet ke Devide korbo ekhon

In [3]:
real_x = data.iloc[:,1].values
real_x   # 1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

In [4]:
real_x = data.iloc[:,1:2].values   # [:,1:2] --> [1,2] = sudu 1 likle eta vector hbe jeta 1 dimentional entity...tai [1,2] liksi --2 disi coz Array banaisi [1,2] diya
real_x   # Array = Matrix...Not Vector # IV

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]], dtype=int64)

In [5]:
real_y = data.iloc[:,2].values 
real_y  # DV

array([  45000,   50000,   60000,   80000,  110000,  150000,  200000,
        300000,  500000, 1000000], dtype=int64)

###### ei khane choto dataset tai Split kora lagbo na ... boro dataset hole Split kora lage Likes 30-40 Data jodi thake 

# Ekhon Simple Linear Regression Model Banabo For Comparison

In [6]:
from sklearn.linear_model import LinearRegression

In [7]:
linear_Reg = LinearRegression()
linear_Reg.fit(real_x,real_y)  # Model Train korlam

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

# Ekhon Polynomial Rgression Model Banabo

In [8]:
from sklearn.preprocessing import PolynomialFeatures

In [9]:
polynomial_reg = PolynomialFeatures() # Shift + tab = diya dekbo
real_x_poly = polynomial_reg.fit_transform(real_x)
real_x_poly   # y = b0 + b1x1**1 + b2x2**2 = PolynomialFeatures() # Shift + tab = diya dekbo   # New IV

array([[  1.,   1.,   1.],
       [  1.,   2.,   4.],
       [  1.,   3.,   9.],
       [  1.,   4.,  16.],
       [  1.,   5.,  25.],
       [  1.,   6.,  36.],
       [  1.,   7.,  49.],
       [  1.,   8.,  64.],
       [  1.,   9.,  81.],
       [  1.,  10., 100.]])

In [10]:
polynomial_reg.fit(real_x_poly,real_y)  # PLR Model

PolynomialFeatures(degree=2, include_bias=True, interaction_only=False,
                   order='C')

In [11]:
linear_Reg2 = LinearRegression()
linear_Reg2.fit(real_x_poly,real_y)   # SLR Model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)